### ISSUE TITLE
O-MI write corrupts findParking result, search radius not working correctly

### ISSUE THREAD

**Issue by fl-ma** [AaltoAsia/O-MI#12]
When adding the attached example to an O-MI node, findParking does not work any longer. Even queries that worked before adding the data (which concern a totally different area) do not return results any more.
[local example second.txt](https://github.com/AaltoAsia/O-MI/files/2294101/local.example.second.txt)

**Comment by fl-ma** [comment]
[local example second v2.txt](https://github.com/AaltoAsia/O-MI/files/2294181/local.example.second.v2.txt)

seems to work with this example, allthough I don't understand why findparking is accepting any search radius but seems to be unable to find two chargers at the same time when they are too far apart.

**Comment by TK009** [comment]
We couldn't reproduce any corruption, but found that findParking `distance` parameter must have double value type: `<value type="xs:double">...` to work correctly. Otherwise it uses the default of one kilometer.

We fixed that by also accepting integers and number strings that can be converted to double.

**Comment by TK009** [comment]
Reopen this issue if there are still problems.
