### ISSUE TITLE
Bugs_EventBased

### ISSUE THREAD

**Issue by skubler** [AaltoAsia/O-MI#5]
Please see enclosed pdf (including the bugs' sequence diagram) for a better understanding of the two bugs.

Bug 1: Multiple Event-based subscriptions (subscribing to only 1 InfoItem)
When performing several/distinct subscriptions, we have to wait a change occurence in the FIRST subscription for receiving (potential) changes that occurred in other subscriptions (e.g., change occurrences that occurred in the 2nd, 3rd subscription...)

Bug 2: Multiple InfotItems subscribed in a SINGLE event-based subscription
When performing ONE subscription including a group of InfoItems, then the server doesn't seem to react (doesn't send any message).

[Bugs_EventBased.pdf](https://github.com/AaltoAsia/O-MI/files/127775/Bugs_EventBased.pdf)

**Comment by TK009** [comment]
Thanks for the report. We have a new version of the subscription logic soon ready and will check this again then.

We probably need more automatic tests for subscriptions.

**Comment by TK009** [comment]
@skubler We couldn't reproduce those bugs. Could you check the following:
1. You are using the latest release or latest code from master branch.
2. Your callback server answers http return code 200 for post requests.
3. The modifications to the InfoItems have newer timestamp than the latest value in the server (or the latest value doesn't have timestamp in the future).
4. The modifications to the InfoItems have different value than the latest value in the server.

I suspect that the problem is with number 3. above. You can also leave the timestamp out when writing values to let the server put it automatically.
